### ISSUE TITLE
Bug: Admin-UI Order of Scenarios in Course 

### ISSUE THREAD

**Issue by ebartz** [boxboat/hobbyfarm-chart#170] opened 2021-12-13 08:06 UTC
**What happened**:
When setting a specific order of scenarios in a course, the CRD will get created in the right order. When you then reload the backend and navigate to that course, the order will be shuffled. When you then save the course again, also the order in the CRD is broken.

**What you expected to happen**:
Wen editing a course in the backend I expect it to keep the order that the resources have in the CRD.

**Comment by jggoebel** [comment] 2022-09-29 13:46
This issue should be fixed with the 2.0.0 changes (https://github.com/hobbyfarm/admin-ui/pull/126) in the Dashboard. This problem was probably caused by multiple parralel requests against `/a/scenario/list`.

**Closed as completed by jggoebel** 2022-09-29 13:46 UTC
Labels: kind/bug
